apiVersion: v1
kind: ConfigMap
metadata:
  name: checkoutservice
data:
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  PAYMENT_SERVICE_ADDR: "paymentservice:50051"
  EMAIL_SERVICE_ADDR: "emailservice:8080"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  CART_SERVICE_ADDR: "cartservice:7070"
  PORT: "5050"
  DISABLE_PROFILER: "1"
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkoutservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: checkoutservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: checkout
          image: srikanthhg/checkoutservice:v1
          ports:
          - containerPort: 5050
          envFrom:
          - configMapRef:
              name: checkoutservice
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP # by default ClusterIP
  selector:
    app: checkoutservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: 5050 #service-port
    targetPort: 5050 #container-port